data:
  orders_path: data/orders.csv
  delays_path: data/partners_delays.csv
  dayoffs_path: data/dayoffs.txt
  celebrations_path: data/celebrations.txt

preprocessing:
  seed: 2021
  date_test_split: 2021-11-16
  prev_cols_cnt: 30
  next_cols_cnt: 7
  eps: 10.0e-7
  test_size: 0.2

lgbm_opt_params:
  - {
    'learning_rate': 0.3,
    'max_depth': 10,
    'metric': mape,
    'min_child_samples': 15,
    'num_leaves': 25,
    'objective': mape,
    'reg_alpha': 0.1,
    'reg_lambda': 0.0,
    'seed': 2021
  }
  - {
    'learning_rate': 0.1,
    'max_depth': 9,
    'metric': mape,
    'min_child_samples': 20,
    'num_leaves': 32,
    'objective': mape,
    'reg_alpha': 0.1,
    'reg_lambda': 0.1,
    'seed': 2021
  }
  - {
    'learning_rate': 0.1,
    'max_depth': 12,
    'metric': mape,
    'min_child_samples': 10,
    'num_leaves': 32,
    'objective': mape,
    'reg_alpha': 0.0,
    'reg_lambda': 0.0,
    'seed': 2021
  }
  - {
    'learning_rate': 0.3,
    'max_depth': 5,
    'metric': 'mape',
    'min_child_samples': 20,
    'num_leaves': 30,
    'objective': mape,
    'reg_alpha': 0.1,
    'reg_lambda': 0.1,
    'seed': 2021
  }
  - {
    'learning_rate': 0.3,
    'max_depth': 9,
    'metric': mape,
    'min_child_samples': 15,
    'num_leaves': 30,
    'objective': mape,
    'reg_alpha': 0.0,
    'reg_lambda': 0.0,
    'seed': 2021
  }
  - {
    'learning_rate': 0.3,
    'max_depth': 5,
    'metric': mape,
    'min_child_samples': 15,
    'num_leaves': 25,
    'objective': mape,
    'reg_alpha': 0.1,
    'reg_lambda': 0.0,
    'seed': 2021
  }
  - {
    'learning_rate': 0.1,
    'max_depth': 12,
    'metric': mape,
    'min_child_samples': 10,
    'num_leaves': 32,
    'objective': mape,
    'reg_alpha': 0.0,
    'reg_lambda': 0.0,
    'seed': 2021
  }
model_path: models/lgbm_model_1.pkl
delay_threshold: 0.05
days_to_feature_calc: 30

